import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import CanvasContainer from "../components/CanvasContainer";
import { Effect } from "../utils/effect";
import styles from "../styles/canvas.module.css";
import { drawBlink, drawMouse } from "../drawFunctions/basic";
import ParticleSystem from "../utils/Particle";

const Home: NextPage = () => {
  const [effectMap, setEffectMap] = useState<Map<string, Effect> | undefined>(
    undefined
  );
  useEffect(() => {
    const temp = new Map<string, Effect>();
    const drawMouseObject: Effect = {
      name: "Draw Mouse",
      drawFunction: drawMouse,
      disabled: false,
      particleSystem: new ParticleSystem(),
    };
    const drawBlinkObject: Effect = {
      name: "Draw Blink",
      drawFunction: drawBlink,
      disabled: true,
    };

    temp.set(drawMouseObject.name, drawMouseObject);
    temp.set(drawBlinkObject.name, drawBlinkObject);
    setEffectMap(temp);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Canvas cool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to stuff!</h1>
      {effectMap && <CanvasContainer effectMap={effectMap} />}
    </div>
  );
};

export default Home;
