import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Canvas, { MousePos } from "../components/Canvas";
import CanvasContainer from "../components/CanvasContainer";
import FunctionList, { FunctionProps } from "../components/FunctionList";
import { Effect } from "../utils/effect";
import styles from "../styles/canvas.module.css";
import { drawBlink, drawMouse } from "../drawFunctions/basic";

const Home: NextPage = () => {
  const [effectMap, setEffectMap] = useState(new Map<string, Effect>());
  useEffect(() => {
    const temp = new Map<string, Effect>(effectMap);
    const drawMouseObject: Effect = {
      name: "Draw Mouse",
      drawFunction: drawMouse,
      disabled: false,
    };
    const drawBlinkObject: Effect = {
      name: "Draw Blink",
      drawFunction: drawBlink,
      disabled: true,
    };

    temp.set(drawMouseObject.name, drawMouseObject);
    temp.set(drawBlinkObject.name, drawBlinkObject);
    setEffectMap(temp);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to stuff!</h1>
      <CanvasContainer effectMap={effectMap} />
    </div>
  );
};

export default Home;
