import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Canvas, { MousePos } from '../components/Canvas'
import FunctionList, { FunctionProps } from '../components/FunctionList'
import {drawMouse, drawBlink} from "../drawFunctions/basic"
import styles from "../styles/canvas.module.css"

const Home: NextPage = () => {

  const [drawFunctions, setDrawFunctions] = useState<Map<string,FunctionProps>>(new Map())

  useEffect(() => {
    const temp = new Map(drawFunctions)
    temp.set("Draw Mouse",{name: "Draw Mouse", drawFunction: drawMouse, disabled:false, disableFunction: toggleEffect} )
    setDrawFunctions(temp)
  },[drawFunctions])

  const toggleEffect = (effect: FunctionProps, toggleTo: boolean) => {
    
    const temp = new Map(drawFunctions)
    
    temp.set(effect.name, {...effect, disabled: toggleTo})
    setDrawFunctions(temp)
  }

  const draw= (ctx: CanvasRenderingContext2D, frameCount: number, mousePos: MousePos| undefined) => {
    ctx.clearRect(0,0,ctx.canvas.width, ctx.canvas.height)
    Array.from(drawFunctions.values()).forEach(drawObject =>{
      if (!drawObject.disabled) {
        drawObject.drawFunction(ctx,frameCount,mousePos) 
      }
      
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Welcome to stuff!</h1>
    <FunctionList functions={Array.from(drawFunctions.values())}/> 
     <Canvas className={styles.canvas} draw={draw} width={900} height={600}/>
    </div>
  )
}

export default Home
